<!DOCTYPE html>
<html lang="fr">
    <head>
        <meta charset="utf-8" />
        <title><?= $data["name"] ?? "Soif 200" ?></title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;500;600;700;800&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="assets/css/style.css" />
    </head>
    <body>
        <?php require "templates/partials/_header.phtml"; ?>
        <?php require "templates/$template.phtml"; ?>
        <?php require "templates/partials/_footer.phtml"; ?>
    </body>
</html>